Repository sequinstream/sequin, pull requests merged in 2025-07, with the labels that each got.

#1884 Add Meilisearch sink routing
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/dynamicRoutingDocs.ts
  assets/svelte/consumers/types.ts
  assets/svelte/functions/Edit.svelte
  assets/svelte/sinks/meilisearch/MeilisearchSinkCard.svelte
  assets/svelte/sinks/meilisearch/MeilisearchSinkForm.svelte
  docs/reference/routing.mdx
  docs/reference/sinks/meilisearch.mdx
  lib/sequin/consumers/meilisearch_sink.ex
  lib/sequin/consumers/routing_function.ex
  lib/sequin/runtime/meilisearch_pipeline.ex
  lib/sequin/runtime/routing/consumers/meilisearch.ex
  lib/sequin/runtime/routing/routing.ex
  lib/sequin/sinks/meilisearch/client.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/functions/edit.ex
  test/sequin/meilisearch_client_test.exs
  test/sequin/meilisearch_sink_test.exs
  test/support/factory/functions_factory.ex
Labels: documentation, size:L, codex

#1895 ✨ Routing for Elasticsearch
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/dynamicRoutingDocs.ts
  assets/svelte/consumers/types.ts
  assets/svelte/functions/Edit.svelte
  assets/svelte/sinks/elasticsearch/ElasticsearchSinkCard.svelte
  assets/svelte/sinks/elasticsearch/ElasticsearchSinkForm.svelte
  docker-compose.yaml
  docs/reference/routing.mdx
  docs/reference/sinks/elasticsearch.mdx
  lib/sequin/consumers/elasticsearch_sink.ex
  lib/sequin/consumers/routing_function.ex
  lib/sequin/runtime/elasticsearch_pipeline.ex
  lib/sequin/runtime/routing/consumers/elasticsearch.ex
  lib/sequin/runtime/routing/routing.ex
  lib/sequin/sinks/elasticsearch/client.ex
  lib/sequin_web/live/functions/edit.ex
  test/sequin/elasticsearch_sink_test.exs
  test/support/factory/consumers_factory.ex
  test/support/factory/functions_factory.ex
Labels: documentation, size:L

#1901 Readme rewrite - first draft
  README.md
Labels: documentation, size:L

#1903 📝 Add docs links between quickstarts, how-tos, and references
  docs/how-to/stream-postgres-to-a-webhook-endpoint.mdx
  docs/how-to/stream-postgres-to-azure-event-hubs.mdx
  docs/how-to/stream-postgres-to-elasticsearch.mdx
  docs/how-to/stream-postgres-to-gcp-pubsub.mdx
  docs/how-to/stream-postgres-to-kafka.mdx
  docs/how-to/stream-postgres-to-kinesis.mdx
  docs/how-to/stream-postgres-to-meilisearch.mdx
  docs/how-to/stream-postgres-to-nats.mdx
  docs/how-to/stream-postgres-to-rabbitmq.mdx
  docs/how-to/stream-postgres-to-redis-stream.mdx
  docs/how-to/stream-postgres-to-redis-string.mdx
  docs/how-to/stream-postgres-to-s2.mdx
  docs/how-to/stream-postgres-to-sequin-stream.mdx
  docs/how-to/stream-postgres-to-sns.mdx
  docs/how-to/stream-postgres-to-sqs.mdx
  docs/how-to/stream-postgres-to-typesense.mdx
  docs/quickstart/azure-event-hubs.mdx
  docs/quickstart/elasticsearch.mdx
  docs/quickstart/gcp-pubsub.mdx
  docs/quickstart/kafka.mdx
  docs/quickstart/kinesis.mdx
  docs/quickstart/meilisearch.mdx
  docs/quickstart/nats.mdx
  docs/quickstart/rabbitmq.mdx
  docs/quickstart/redis-stream.mdx
  docs/quickstart/redis-string.mdx
  docs/quickstart/redpanda.mdx
  docs/quickstart/s2.mdx
  docs/quickstart/sequin-stream.mdx
  docs/quickstart/sns.mdx
  docs/quickstart/sqs.mdx
  docs/quickstart/typesense.mdx
  docs/quickstart/webhooks.mdx
  docs/reference/sinks/azure-event-hubs.mdx
  docs/reference/sinks/elasticsearch.mdx
  docs/reference/sinks/gcp-pubsub.mdx
  docs/reference/sinks/kafka.mdx
  docs/reference/sinks/kinesis.mdx
  docs/reference/sinks/meilisearch.mdx
  docs/reference/sinks/nats.mdx
  docs/reference/sinks/rabbitmq.mdx
  docs/reference/sinks/redis-stream.mdx
  docs/reference/sinks/redis-string.mdx
  docs/reference/sinks/s2.mdx
  docs/reference/sinks/sequin-stream.mdx
  docs/reference/sinks/sns.mdx
  docs/reference/sinks/sqs.mdx
  docs/reference/sinks/typesense.mdx
  docs/reference/sinks/webhooks.mdx
Labels: documentation, size:L

#1918 ♻️ Small changes to meilisearch docker / default routing
  docker-compose.yaml
  lib/sequin/runtime/routing/consumers/meilisearch.ex
Labels: size:XS

#1907 Updates to SlotProducer from code review
  lib/sequin/runtime/slot_producer/processor.ex
  lib/sequin/runtime/slot_producer/slot_producer.ex
  lib/sequin/runtime/slot_producer/supervisor.ex
  test/sequin/postgres_replication_test.exs
  test/sequin/runtime/slot_producer/integration_test.exs
  test/sequin/runtime/slot_producer/slot_producer_test.exs
Labels: size:L, lgtm

#1906 Add routing for RabbitMQ sink
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/dynamicRoutingDocs.ts
  assets/svelte/consumers/types.ts
  assets/svelte/functions/Edit.svelte
  assets/svelte/sinks/rabbitmq/RabbitMqSinkCard.svelte
  assets/svelte/sinks/rabbitmq/RabbitMqSinkForm.svelte
  config/test.exs
  docker-compose.yaml
  docs/quickstart/rabbitmq.mdx
  docs/reference/routing.mdx
  docs/reference/sinks/rabbitmq.mdx
  lib/sequin/consumers/rabbitmq_sink.ex
  lib/sequin/consumers/routing_function.ex
  lib/sequin/runtime/rabbitmq_pipeline.ex
  lib/sequin/runtime/routing/consumers/rabbitmq.ex
  lib/sequin/runtime/routing/routing.ex
  lib/sequin/sinks/rabbitmq/client.ex
  lib/sequin/sinks/rabbitmq/rabbitmq.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/functions/edit.ex
  lib/sequin_web/live/sink_consumers/show.ex
  test/sequin/rabbitmq_pipeline_test.exs
  test/sequin/rabbitmq_sink_test.exs
  test/support/factory/consumers_factory.ex
  test/support/factory/functions_factory.ex
Labels: documentation, sink-rabbitmq, size:XL, codex

#1925 Add routing for Azure Event Hub sink
  assets/svelte/consumers/ShowSink.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/SinkHttpPushForm.svelte
  assets/svelte/consumers/dynamicRoutingDocs.ts
  assets/svelte/consumers/types.ts
  assets/svelte/functions/Edit.svelte
  assets/svelte/http_endpoints/Show.svelte
  assets/svelte/sinks/azure_event_hub/AzureEventHubSinkCard.svelte
  assets/svelte/sinks/azure_event_hub/AzureEventHubSinkForm.svelte
  assets/svelte/sinks/gcp_pubsub/GcpPubsubSinkCard.svelte
  assets/svelte/sinks/kinesis/KinesisSinkCard.svelte
  assets/svelte/sinks/meilisearch/MeilisearchSinkCard.svelte
  assets/svelte/sinks/nats/NatsSinkCard.svelte
  assets/svelte/sinks/redis-stream/RedisStreamSinkCard.svelte
  assets/svelte/sinks/redis-string/RedisStringSinkCard.svelte
  assets/svelte/sinks/s2/S2SinkCard.svelte
  assets/svelte/sinks/sns/SnsSinkCard.svelte
  assets/svelte/sinks/sqs/SqsSinkCard.svelte
  assets/svelte/sinks/typesense/TypesenseSinkCard.svelte
  docs/reference/routing.mdx
  docs/reference/sinks/azure-event-hubs.mdx
  lib/sequin/consumers/azure_event_hub_sink.ex
  lib/sequin/consumers/routing_function.ex
  lib/sequin/runtime/azure_event_hub_pipeline.ex
  lib/sequin/runtime/routing/consumers/azure_event_hub.ex
  lib/sequin/runtime/routing/routing.ex
  lib/sequin/sinks/azure/event_hub.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/functions/edit.ex
  test/sequin/azure_event_hub_pipeline_test.exs
  test/sequin/azure_event_hub_sink_test.exs
  test/support/factory/consumers_factory.ex
  test/support/factory/functions_factory.ex
Labels: documentation, sink-azure-eventhubs, size:XL, codex

#1927 🧹 Delete DOCTODO
  docs/how-to/stream-postgres-to-kafka.mdx
Labels: documentation, size:XS

#1938 🐛 Do not expect id for database primaries
  lib/sequin_web/controllers/postgres_database_json.ex
  test/sequin_web/controllers/postgres_database_controller_test.exs
  test/support/factory/databases_factory.ex
Labels: bug, size:M

#1939 🔧 Fix flaky connection_cache_tests
  test/sequin/connection_cache_test.exs
Labels: reliability, size:XS

#1940 ✨ Typesense timeout_seconds to 3600
  assets/svelte/consumers/types.ts
  assets/svelte/sinks/typesense/TypesenseSinkCard.svelte
  assets/svelte/sinks/typesense/TypesenseSinkForm.svelte
  lib/sequin/consumers/typesense_sink.ex
Labels: enhancement, size:M

#1943 feat(functions): Allow for using JSON in functions
  docs/snippets/function-transform-snippet.mdx
  lib/sequin/functions/minielixir/validator.ex
Labels: documentation, enhancement, size:XS

#1953 🔮 Regex and Integer in MiniElixir
  docs/snippets/function-transform-snippet.mdx
  lib/sequin/functions/minielixir/validator.ex
  lib/sequin_web/live/functions/auto_complete.ex
  mix.exs
  mix.lock
Labels: documentation, size:S

#1955 💄 Show table name on messages tab
  assets/svelte/consumers/ShowMessages.svelte
  lib/sequin/consumers/acknowledged_messages/acknowledged_message.ex
  lib/sequin/consumers/acknowledged_messages/acknowledged_messages.ex
  lib/sequin_web/live/sink_consumers/show.ex
Labels: ux-enhancement, size:M

#1956 ✨ Add Database restart button
  assets/svelte/databases/ShowHeader.svelte
  lib/sequin_web/live/databases/show.ex
Labels: enhancement, size:M

#1928 feat(slot_producer): Updates after QA1
  lib/sequin/databases/connection_cache.ex
  lib/sequin/error.ex
  lib/sequin/havoc.ex
  lib/sequin/iex_helpers.ex
  lib/sequin/postgres/postgres.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_processor_server.ex
  lib/sequin/runtime/slot_producer/pipeline_defaults.ex
  lib/sequin/runtime/slot_producer/reorder_buffer.ex
  lib/sequin/runtime/slot_producer/slot_producer.ex
  lib/sequin/runtime/slot_producer/supervisor.ex
  test/sequin/postgres_replication_test.exs
Labels: enhancement, size:L

#1921 Use GenStage pipeline
  .formatter.exs
  .iex.exs
  .zed/tasks.json
  AGENTS.md
  config/config.exs
  config/test.exs
  docker/dashboard.json
  grafana/dashboards/sequin.json
  lib/sequin.ex
  lib/sequin/application.ex
  lib/sequin/databases/connection_cache.ex
  lib/sequin/databases/postgres_database.ex
  lib/sequin/error.ex
  lib/sequin/generate_behaviour.ex
  lib/sequin/havoc.ex
  lib/sequin/health/health.ex
  lib/sequin/iex_helpers.ex
  lib/sequin/postgres/postgres.ex
  lib/sequin/replication/replication.ex
  lib/sequin/runtime/consumer_producer.ex
  lib/sequin/runtime/message.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/runtime/message_handler_stub.ex
  lib/sequin/runtime/slot_message_handler.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
  lib/sequin/runtime/slot_processor_server.ex
  lib/sequin/runtime/slot_processor_supervisor.ex
  lib/sequin/runtime/slot_producer/batch.ex
  lib/sequin/runtime/slot_producer/batch_marker.ex
  lib/sequin/runtime/slot_producer/pipeline_defaults.ex
  lib/sequin/runtime/slot_producer/postgres_relation_hash_cache.ex
  lib/sequin/runtime/slot_producer/processor.ex
  lib/sequin/runtime/slot_producer/processor_behavior.ex
  lib/sequin/runtime/slot_producer/relation.ex
  lib/sequin/runtime/slot_producer/reorder_buffer.ex
  lib/sequin/runtime/slot_producer/slot_producer.ex
  lib/sequin/runtime/slot_producer/supervisor.ex
  lib/sequin_web/controllers/postgres_replication_controller.ex
  mix.exs
  mix.lock
  test/sequin/debounced_logger_test.exs
  test/sequin/postgres_replication_test.exs
  test/sequin/runtime/slot_producer/integration_test.exs
  test/sequin/runtime/slot_producer/reorder_buffer_test.exs
  test/sequin/runtime/slot_producer/slot_producer_test.exs
  test/sequin/slot_message_handler_test.exs
  test/sequin_web/controllers/pull_controller_test.exs
  test/support/factory/replication_factory.ex
  test/support/mocks.ex
  test/support/models/test_event_log_partioned.ex
  test/support/replication_slots.ex
Labels: bug, enhancement, refactor, size:XXL

#1965 feat(slot_producer): Use async_info to propagate batch markers
  lib/sequin/havoc.ex
  lib/sequin/runtime/slot_producer/processor.ex
  lib/sequin/runtime/slot_producer/reorder_buffer.ex
Labels: enhancement, size:XS

#1924 🗑️ Remove libcluster
  config/dev.exs
  config/runtime.exs
  config/test.exs
  lib/sequin/application.ex
  lib/sequin/libcluster/postgres_strategy.ex
  mix.exs
Labels: refactor, size:L

#1960 ✨ Generate proper group_id, idempotency key in backfills
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/message.ex
  lib/sequin/runtime/slot_producer/processor.ex
  lib/sequin/runtime/table_reader.ex
  test/support/factory/replication_factory.ex
Labels: enhancement, size:L, lgtm

#1967 Support List, `with` in MiniElixir
  docs/snippets/function-transform-snippet.mdx
  lib/sequin/functions/minielixir/validator.ex
  test/sequin/minielixir_test.exs
Labels: size:L

#1957 💄 Make backfills form expandable for backfills tab
  assets/svelte/components/BackfillForm.svelte
  assets/svelte/consumers/ShowBackfills.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
Labels: ux-enhancement, size:XS

#1961 ✨ Backfill start position per table
  assets/svelte/components/BackfillForm.svelte
  assets/svelte/components/Datetime.svelte
  assets/svelte/consumers/ShowBackfills.svelte
  lib/sequin_web/live/sink_consumers/show.ex
  test/sequin_web/live/sink_consumers_live_show_test.exs
  test/support/conn_case.ex
Labels: size:XL

#1968 ✨ /backfills and consumer/create
  assets/svelte/components/BackfillForm.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  lib/sequin/consumers/consumers.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/sink_consumers/show.ex
Labels: size:L

#1975 ✨ Message grouping (simple) in the console
  assets/svelte/consumers/ShowSink.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/types.ts
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/sink_consumers/show.ex
Labels: enhancement, size:M

#1978 ⚙️ Update from onboarding session
  CONTRIBUTING.md
Labels: size:S

#1979 ⚡️ Reorder ready batch management
  lib/sequin/runtime/slot_producer/reorder_buffer.ex
Labels: size:XS

#1980 Add flush batch timer auditor
  lib/sequin/runtime/slot_producer/reorder_buffer.ex
Labels: size:M

#1984 🐛 Assign %Message{batch_idx: } when producing
  lib/sequin/runtime/slot_producer/slot_producer.ex
Labels: bug, size:XS

#1985 ⚡️ SQS / SNS fast by default
  lib/sequin/aws/sqs.ex
  lib/sequin/runtime/sns_pipeline.ex
  lib/sequin/runtime/sqs_pipeline.ex
  test/sequin/aws_sqs_test.exs
Labels: sqs, size:S, lgtm

#1987 Change default log format back to ConsoleLogger
  config/runtime.exs
  docs/reference/configuration.mdx
  lib/sequin/config_parser.ex
Labels: documentation, size:L

#2002 Make Typesense to be default fast
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/sinks/elasticsearch/ElasticsearchSinkForm.svelte
  assets/svelte/sinks/meilisearch/MeilisearchSinkForm.svelte
  assets/svelte/sinks/typesense/TypesenseSinkForm.svelte
  lib/sequin/consumers/typesense_sink.ex
  lib/sequin/runtime/typesense_pipeline.ex
Labels: size:L, lgtm

#2018 ✅ Tests passing
  lib/sequin/transforms/transforms.ex
Labels: size:XS

#2010 ✨ Functions/edit console
  assets/svelte/functions/Edit.svelte
  assets/svelte/functions/EditableArgument.svelte
  assets/svelte/functions/types.ts
  lib/sequin/consumers/consumers.ex
  lib/sequin_web/live/functions/edit.ex
Labels: enhancement, size:M

#2020 🐛 Gate enrichment functions with :function_transforms
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/sql_enrichment_function.ex
Labels: bug, size:M

#2021 ♻️ %SqlEnrichmentFunction{} -> %EnrichmentFunction
  config/dev.exs
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/enrichment_function.ex
  lib/sequin/consumers/function.ex
  lib/sequin/transforms/transforms.ex
  lib/sequin_web/live/functions/edit.ex
  lib/sequin_web/live/sink_consumers/show.ex
  test/sequin/consumers_test.exs
  test/support/factory/functions_factory.ex
Labels: size:M

#2013 Add routing to messages tab
  assets/svelte/consumers/ShowMessages.svelte
  assets/svelte/functions/Edit.svelte
  lib/sequin_web/live/sink_consumers/show.ex
Labels: ux-enhancement, size:L

#2024 ✨ GCP PubSub batch by messages and bytes
  lib/sequin/runtime/gcp_pubsub_pipeline.ex
  lib/sequin/runtime/sink_pipeline.ex
  lib/sequin/sinks/gcp/pubsub.ex
  test/sequin/gcp_pubsub_pipeline_test.exs
  test/sequin/gcp_pubsub_test.exs
  test/sequin/sink_pipeline_test.exs
Labels: sink-gcp-pubsub, size:L

#2030 🛠️ Remove `test/support` from being compiled in :dev mode
  mix.exs
Labels: refactor, size:XS

#2041 🛠️ Fix exporting schema and table names for change_retentions
  lib/sequin/consumers/consumers.ex
  test/sequin/transforms_test.exs
Labels: bug, size:S, lgtm
