Repository sequinstream/sequin, pull requests merged in 2025-05, with the labels that each got.

#1398 🐛 Fix reporting of replication slot size
  lib/sequin/health/check_postgres_replication_slot_worker.ex
  lib/sequin/metrics/prometheus.ex
Labels: size:S

#1399 [metrics] Add db name to replication_slot_size
  lib/sequin/health/check_postgres_replication_slot_worker.ex
  lib/sequin/metrics/prometheus.ex
Labels: size:S

#1401 Revert "[slotprocessorserver] fast reject messages not destined for any sink"
  lib/sequin/replication/replication.ex
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
  lib/sequin/runtime/postgres_adapter/decoder.ex
  lib/sequin/runtime/slot_processor_server.ex
  test/sequin/postgres_replication_test.exs
Labels: size:L

#1403 [slotprocessorserver] check if heartbeats are missing despite LSN advance
  lib/sequin/runtime/slot_processor_server.ex
Labels: size:L, lgtm

#1402 Add support for max_retry_count to limit Webhook delivery attempts
  assets/svelte/consumers/ShowMessages.svelte
  assets/svelte/consumers/ShowSink.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/SinkHttpPushForm.svelte
  lib/sequin/consumers/acknowledged_messages/acknowledged_message.ex
  lib/sequin/consumers/acknowledged_messages/acknowledged_messages.ex
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/runtime/sink_pipeline.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/sink_consumers/show.ex
  priv/repo/migrations/20250507120049_add_max_retry_count_to_sink_consumers.exs
  test/sequin/slot_message_store_test.exs
Labels: enhancement, size:L

#1404 [max_retry_count] Add YAML + API
  docs/management-api/sink-consumers/create.mdx
  docs/management-api/sink-consumers/update.mdx
  docs/reference/sinks/overview.mdx
  docs/snippets/sink-consumer-list-response-example-snippet.mdx
  docs/snippets/sink-consumer-response-snippet.mdx
  docs/snippets/sink-consumer-single-response-example-snippet.mdx
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/transforms/transforms.ex
  test/sequin/slot_message_store_test.exs
  test/sequin/yaml_loader_test.exs
  test/sequin_web/controllers/sink_consumer_controller_test.exs
Labels: size:M

#1405 Add `load_shedding_policy` to sinks
  docs/management-api/sink-consumers/create.mdx
  docs/management-api/sink-consumers/update.mdx
  docs/reference/sinks/overview.mdx
  docs/snippets/sink-consumer-list-response-example-snippet.mdx
  docs/snippets/sink-consumer-response-snippet.mdx
  docs/snippets/sink-consumer-single-response-example-snippet.mdx
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/health/event.ex
  lib/sequin/health/health.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/transforms/transforms.ex
  lib/sequin_web/live/sink_consumers/show.ex
  priv/repo/migrations/20250508232836_add_load_shedding_policy_to_sink_consumers.exs
  test/sequin/slot_message_store_test.exs
  test/sequin_web/controllers/sink_consumer_controller_test.exs
Labels: size:L

#1406 Comment out flaky test line
  test/sequin/postgres_replication_test.exs
Labels: size:XS

#1407 🐛 Fix getter for slot_name in CheckPostgresReplicationSlotWorker
  lib/sequin/health/check_postgres_replication_slot_worker.ex
Labels: size:XS

#1411 chore: reorganize deps in mix.exs for clarity
  mix.exs
Labels: dependencies, size:S, lgtm

#1412 Always run signoff GH action
  .github/workflows/pr-checks.yml
Labels: size:XS

#1410 feat: accept _{var} in mini-elixir function headers
  lib/sequin/transforms/minielixir/validator.ex
  test/sequin/minielixir_test.exs
Labels: enhancement, size:S, lgtm

#1408 chore: use mfa in timer:tc where possible
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_processor_server.ex
  lib/sequin/sinks/redis/client.ex
  lib/sequin_web/controllers/pull_controller.ex
  lib/sequin_web/live/transforms/edit.ex
Labels: size:M, lgtm

#1374 feat: show clearer connectivity errors and run extra checks for IPv6
  lib/sequin/network_utils.ex
Labels: size:M

#1391 [test] tell you when you have to ecto.reset unboxedrepo
  test/support/unboxed_repo/migrations/20240816005458_create_test_tables.exs
  test/test_helper.exs
Labels: size:S

#1396 dev: add tidewave to have additional phoenix-related features via MCP
  lib/sequin_web/endpoint.ex
  mix.exs
  mix.lock
Labels: dependencies, size:XS, lgtm

#1418 Fix formatting
  test/support/unboxed_repo/migrations/20240816005458_create_test_tables.exs
  test/test_helper.exs
Labels: size:S

#1419 Stringify group_id
  lib/sequin/runtime/message_handler.ex
Labels: size:XS

#1425 Fix transforms YAML flat format
  lib/sequin/yaml_loader.ex
  test/sequin/yaml_loader_test.exs
Labels: bug, size:S

#1426 fix: put back execution redis command in fun
  lib/sequin/sinks/redis/client.ex
Labels: bug, size:XS

#1414 🪞🐘 Support for Postgres Replicas
  assets/svelte/databases/Form.svelte
  docker/replica-cdc-dev/README.md
  docker/replica-cdc-dev/docker-compose.yaml
  docker/replica-cdc-dev/init-primary.sh
  docker/replica-cdc-dev/init-replica.sh
  docs/management-api/postgres_databases/create.mdx
  docs/management-api/postgres_databases/update.mdx
  docs/reference/databases.mdx
  docs/reference/sequin-yaml.mdx
  lib/sequin/databases/connection_cache.ex
  lib/sequin/databases/databases.ex
  lib/sequin/databases/postgres_database.ex
  lib/sequin/databases/postgres_database_primary.ex
  lib/sequin/health/check_postgres_replication_slot_worker.ex
  lib/sequin/runtime/slot_processor_server.ex
  lib/sequin/runtime/slot_processor_supervisor.ex
  lib/sequin/transforms/transforms.ex
  lib/sequin/yaml_loader.ex
  lib/sequin_web/controllers/postgres_database_controller.ex
  lib/sequin_web/controllers/postgres_database_json.ex
  lib/sequin_web/live/databases/form.ex
  priv/repo/migrations/20250505234910_add_primary_jsonb_to_postgresdatabase.exs
  test/sequin/yaml_loader_test.exs
Labels: documentation, size:XXL

#1431 Don't factor max system memory into individual SMS maxes
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/slot_message_store.ex
  test/sequin/consumers_test.exs
  test/sequin/slot_message_store_test.exs
Labels: size:M

#1430 typesense: granular failure
  lib/sequin/runtime/typesense_pipeline.ex
  lib/sequin/sinks/typesense/client.ex
Labels: size:M, lgtm

#1434 Default `pool_size=3` from primary db connection pool
  lib/sequin/databases/postgres_database.ex
Labels: size:XS

#1395 fix: improve full page forms to avoid using a modal
  assets/svelte/components/CodeWithCopy.svelte
  assets/svelte/components/FullPageForm.svelte
  assets/svelte/consumers/GroupColumnsForm.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/databases/Form.svelte
  assets/svelte/http_endpoints/Form.svelte
  assets/svelte/wal_pipelines/Form.svelte
  lib/sequin_web/live/databases/form.ex
  lib/sequin_web/live/http_endpoints/form.ex
  lib/sequin_web/live/sink_consumers/form.ex
  lib/sequin_web/live/sink_consumers/index.ex
  lib/sequin_web/live/wal_pipelines/form.ex
  lib/sequin_web/router.ex
Labels: size:XL

#1433 ✨ use `signoff` both for local and gh actions
  .github/workflows/pr-checks.yml
Labels: size:XS

#1439 Simplify homebrew install instructions
  docs/reference/cli/overview.mdx
Labels: size:XS

#1423 feat: add CLI page with setup instructions and links to documentation
  assets/svelte/Button.svelte
  assets/svelte/cli/Index.svelte
  assets/svelte/components/Sidenav.svelte
  lib/sequin_web/live/cli_live.ex
  lib/sequin_web/router.ex
Labels: documentation, cli, size:L, lgtm

#1432 fix: improve yaml load for `sinks.max_retry_count`, `sinks.active_backfill` and `http_endpoints.encrypted_headers`
  lib/sequin/transforms/transforms.ex
  test/sequin_web/controllers/yaml_controller_test.exs
  test/support/models/character.ex
Labels: bug, size:M, lgtm

#1441 fix: remove the brew tap command from CopyIcon for cli install
  assets/svelte/cli/Index.svelte
Labels: cli, size:XS

#1420 fix: Message Grouping card form improvements
  assets/svelte/components/ui/card/expandable-card-header.svelte
  assets/svelte/components/ui/card/expandable-card.svelte
  assets/svelte/consumers/GroupColumnsForm.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
Labels: ux-enhancement, size:L

#1444 ✨ Support redis databases for config redis
  docs/reference/configuration.mdx
  lib/sequin/redis.ex
Labels: documentation, size:L, lgtm

#1443 👷 Tweaks to pr-checks.yml
  .github/workflows/signoff-commit.yml
  test/sequin_web/controllers/yaml_controller_test.exs
Labels: size:S

#1445 Test using WarpBuild to build new docker images
  .github/workflows/docker-build.yml
Labels: size:S

#1446 [Docs] Fix outbound links
  docs/guides/temporal.mdx
  docs/guides/trigger-dev.mdx
  docs/reference/sinks/nats.mdx
Labels: size:XS

#1447 ✨ Deep link from message delivery error to messages tab
  assets/svelte/consumers/ShowMessages.svelte
  lib/sequin/health/check.ex
  lib/sequin/health/event.ex
  lib/sequin/health/health.ex
  lib/sequin/runtime/sink_pipeline.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
  lib/sequin_web/live/sink_consumers/show.ex
  lib/sequin_web/router.ex
Labels: enhancement, cli, size:L, lgtm

#1440 [minielixir] better handling for assignments, guards, etc
  lib/sequin/transforms/minielixir.ex
  lib/sequin/transforms/minielixir/validator.ex
  test/sequin/minielixir_test.exs
Labels: size:L, lgtm

#1456 Use `@derive` to filter sensitive sink fields out from logs
  lib/sequin/consumers/azure_event_hub_sink.ex
  lib/sequin/consumers/elasticsearch_sink.ex
  lib/sequin/consumers/kafka_sink.ex
  lib/sequin/consumers/rabbitmq_sink.ex
  lib/sequin/consumers/redis_stream_sink.ex
  lib/sequin/consumers/redis_string_sink.ex
  lib/sequin/consumers/sns_sink.ex
  lib/sequin/consumers/sqs_sink.ex
Labels: sink-sqs, sink-kafka, sink-rabbitmq, sink-azure-eventhubs, size:XS

#1457 In filters, do not show comparison value when user selects IS NULL or IS NOT NULL
  assets/svelte/components/FilterForm.svelte
Labels: size:M

#1460 [sqs] handle un-fifo-ifying a sink's queue
  lib/sequin/consumers/sqs_sink.ex
Labels: sink-sqs, size:XS, lgtm

#1463 💚 Fix flaky test by increasing timeout
  test/sequin/connection_cache_test.exs
Labels: size:XS

#1459 [minielixir] propagate line number in errors
  lib/sequin/transforms/minielixir.ex
  lib/sequin/transforms/minielixir/validator.ex
  test/sequin/transforms_test.exs
Labels: size:M, lgtm

#1466 🐛 Fix consumer message serialization of struct types
  lib/sequin/changeset.ex
  lib/sequin/consumers/consumer_event.ex
  lib/sequin/consumers/consumer_event_data.ex
  lib/sequin/consumers/consumer_record.ex
  lib/sequin/consumers/consumer_record_data.ex
  lib/sequin/consumers/consumers.ex
  lib/sequin/postgres/postgres.ex
  test/changeset_test.exs
  test/sequin/consumer_record_test.exs
  test/sequin/consumers_test.exs
Labels: bug, size:L, lgtm

#1467 [slotmessagestore] more granular flush batching
  config/test.exs
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
  test/sequin/slot_message_store_state_test.exs
  test/sequin/slot_message_store_test.exs
Labels: size:L, lgtm

#1468 More process stats, carve-out for erroneous consumer
  lib/sequin/runtime/sink_pipeline.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
Labels: size:M

#1475 ⚙️ Only consider physical replicas as replicas
  docker/replica-cdc-dev/init-primary.sh
  docker/replica-cdc-dev/init-replica.sh
  lib/sequin/databases/databases.ex
Labels: size:M

#1476 fix: show missing Transform Function form validation errors
  assets/svelte/transforms/Edit.svelte
Labels: bug, size:M, lgtm

#1479 ⚡️ Remove State.pop_blocked_messages
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
  test/sequin/slot_message_store_state_test.exs
  test/sequin/slot_message_store_test.exs
Labels: refactor, size:L

#1478 add clock drift metrics
  lib/sequin/runtime/slot_processor_server.ex
  lib/sequin/time.ex
Labels: enhancement, size:M

#1480 📏 Add busy_percent to ProcessMetrics
  lib/sequin/process_metrics.ex
Labels: enhancement, size:S

#1481 ✨ SlotMessageStore with ProcessMetrics
  lib/sequin/process_metrics.ex
  lib/sequin/runtime/slot_message_store.ex
Labels: size:XL

#1483 📢 Log why verify_heartbeat succeeds
  lib/sequin/runtime/slot_processor_server.ex
Labels: size:M

#1485 ✨ Log confirmed_flush and restart lsns
  lib/sequin/health/check_postgres_replication_slot_worker.ex
  lib/sequin/postgres/postgres.ex
  lib/sequin/replication/replication.ex
Labels: size:M

#1484 Use LSN from database as `heartbeat_emitted_lsn`
  lib/sequin/postgres/postgres.ex
  lib/sequin/runtime/slot_processor_server.ex
Labels: size:S

#1488 Disable pagerduty alerts for SinkConsumers
  lib/sequin/health/health.ex
Labels: size:XS

#1477 fix database replica primary form population
  lib/sequin_web/live/databases/form.ex
Labels: size:S, lgtm

#1487 Check replication lag properly for replicas
  lib/sequin/postgres/postgres.ex
Labels: size:S, lgtm

#1469 fix: only display message not_visible_until date if its defined
  assets/svelte/consumers/ShowMessages.svelte
Labels: bug, size:XS, lgtm

#1473 [minielixir] handle empty cond & other errors
  lib/sequin/consumers/consumers.ex
  lib/sequin/transforms/minielixir/validator.ex
  test/sequin/minielixir_test.exs
Labels: size:S, lgtm

#1489 Show 'Edit database' in title when editing
  assets/svelte/databases/Form.svelte
Labels: size:XS

#1491 Don't log every single keepalive we receive
  lib/sequin/runtime/slot_processor_server.ex
Labels: size:XS

#1500 🐛 Handle nil confirmed_flush / restart lsns
  lib/sequin/postgres/postgres.ex
Labels: bug, size:XS

#1499 ⚙️ Oban queues
  config/config.exs
  lib/sequin/check_system_health_worker.ex
  lib/sequin/databases/create_replication_slot_worker.ex
  lib/sequin/health/check_postgres_replication_slot_worker.ex
  lib/sequin/health/check_sink_configuration_worker.ex
  lib/sequin/health/kickoff_check_http_endpoint_health_worker.ex
  lib/sequin/health/kickoff_check_postgres_replication_slot_worker.ex
  lib/sequin/health/kickoff_check_sink_configuration_worker.ex
  lib/sequin/health/snapshot_health_worker.ex
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
  lib/sequin/runtime/database_lifecycle_event_worker.ex
  lib/sequin/runtime/init_backfill_stats_worker.ex
  test/sequin/transforms_test.exs
Labels: enhancement, size:M

#1492 💄 Format errors for sequin config export/plan/apply
  cli/cli/util.go
  cli/config/config.go
  lib/sequin/error.ex
  lib/sequin/transforms/transforms.ex
  test/sequin_web/controllers/yaml_controller_test.exs
Labels: cli, size:L

#1514 ✨ Support cluster with hashtags etc.
  lib/sequin/metrics/store.ex
  lib/sequin/redis.ex
  lib/sequin/runtime/message_ledgers.ex
Labels: enhancement, size:L, lgtm

#1505 Force preload ecto entities when creating MessageHandler context (avoid stale!)
  lib/sequin/runtime/message_handler.ex
Labels: size:S, lgtm

#1506 ♻️ Rename low_watermark_wal_cursor to safe_wal_cursor
  lib/sequin/replication/replication.ex
  lib/sequin/runtime/slot_processor_server.ex
  test/sequin/postgres_replication_test.exs
Labels: refactor, size:M, lgtm

#1507 ♻️ Rename get_commit_lsn to get_safe_wal_cursor
  lib/sequin/runtime/slot_processor_server.ex
Labels: refactor, size:S, lgtm

#1508 ♻️ Combine the two ack handler functions
  lib/sequin/runtime/slot_processor_server.ex
Labels: refactor, size:M, lgtm

#1509 ♻️ Collapse get_safe_wal_cursor
  lib/sequin/runtime/slot_processor_server.ex
Labels: refactor, size:M, lgtm

#1510 ♻️ Return last_flushed_wal_cursor from safe_wal_cursor_fn
  lib/sequin/runtime/slot_processor_server.ex
Labels: refactor, size:XS, lgtm

#1511 ♻️ Extract out update_safe_wal_cursor function
  lib/sequin/runtime/slot_processor_server.ex
Labels: refactor, size:M, lgtm

#1512 ♻️ Update safe_wal_cursor on an independent interval
  lib/sequin/runtime/slot_processor_server.ex
Labels: refactor, size:S, lgtm

#1513 ♻️ Send ack messages on an interval
  lib/sequin/runtime/slot_processor_server.ex
Labels: size:M, lgtm

#1520 🐛 Allow transform removal from sink
  assets/svelte/consumers/SinkConsumerForm.svelte
Labels: size:XS

#1521 🗑️ Delete SlotMessageStore bench
  bench/slot_message_store_state.ex
  test/sequin/bench_test.exs
Labels: size:L

#1458 fix: workaround to fix PGHOST-related defaults picked by Postgrex
  lib/sequin/databases/postgres_database.ex
Labels: size:XS, lgtm

#1493 fix: avoid saving form to local storage if submission was successful
  assets/svelte/databases/Form.svelte
Labels: bug, size:XS

#1494 fix: only show database exit confirm dialog when form is dirty
  assets/svelte/databases/Form.svelte
  lib/sequin/databases/postgres_database.ex
  lib/sequin_web/live/databases/form.ex
Labels: size:S

#1496 fix: update sequences inline on creating sink consumer to avoid race condition
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
Labels: bug, size:S

#1527 [SlotProcessorServer] Add Task.async_stream call to better support many sink_consumers
  lib/sequin/runtime/slot_message_handler.ex
  lib/sequin/runtime/slot_processor_server.ex
Labels: size:M

#1533 chore: replace Enum.map with Enum.each for side effects
  lib/sequin/health/kickoff_check_http_endpoint_health_worker.ex
  lib/sequin/health/kickoff_check_postgres_replication_slot_worker.ex
  lib/sequin/health/kickoff_check_sink_configuration_worker.ex
  lib/sequin/runtime/sink_pipeline.ex
Labels: refactor, size:XS

#1501 fix: unify consumer sink :new and :edit into a single form live view
  assets/svelte/consumers/SinkConsumerForm.svelte
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/sink_consumers/form.ex
  lib/sequin_web/live/sink_consumers/show.ex
  lib/sequin_web/router.ex
Labels: refactor, size:L

#1539 Add AGENTS.md
  AGENTS.md
Labels: size:M

#1540 🐛 Fix idempotency key in example
  lib/sequin/consumers/consumers.ex
Labels: size:XS

#1535 ⚡️ Improved UI for Functions dashboard. Render publication and replication slot name for the databases index screen as well
  assets/svelte/components/DeleteFunctionDialog.svelte
  assets/svelte/consumers/SinkIndex.svelte
  assets/svelte/databases/Index.svelte
  assets/svelte/databases/Show.svelte
  assets/svelte/transforms/Edit.svelte
  assets/svelte/transforms/Index.svelte
  lib/sequin_web/live/databases/show.ex
  lib/sequin_web/live/transforms/index.ex
Labels: ux-enhancement, size:L

#1541 💄 Convert functions to full page form
  assets/svelte/transforms/Edit.svelte
  lib/sequin_web/live/transforms/edit.ex
Labels: ux-enhancement, size:XXL

#1524 🗂️ max_storage bytes
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
  priv/repo/migrations/20250516225918_add_max_storage_mb_to_sink_consumers.exs
  test/support/factory/consumers_factory.ex
Labels: ux-enhancement, size:M, lgtm

#1525 ✨ Load messages from disk into SMS respecting max_memory_bytes
  lib/sequin/runtime/slot_message_store.ex
  test/sequin/slot_message_store_test.exs
  test/support/factory/consumers_factory.ex
Labels: size:L, lgtm

#1528 ✨ Respect max memory and storage for SMS.put_messages
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
  test/sequin/consumers_test.exs
  test/sequin/slot_message_store_test.exs
Labels: enhancement, size:L

#1529 ✨ pull messages from disk when under half of limits
  lib/sequin/runtime/slot_message_store.ex
  test/sequin/slot_message_store_test.exs
Labels: size:L, lgtm

#1546 Respect database.ssl=false
  lib/sequin_web/live/databases/form.ex
Labels: size:XS

#1531 🐛 Make this safe if MAX_MEMORY_MB is reduced
  lib/sequin/runtime/slot_message_store.ex
Labels: bug, size:XS

#1532 ♻️ Share stream function for SMS
  lib/sequin/runtime/slot_message_store.ex
  test/sequin/slot_message_store_test.exs
Labels: size:L

#1544 ✅ QA additions
  lib/sequin/consumers/http_push_sink.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin_web/controllers/push_webhook_controller.ex
Labels: size:S

#1504 ✨ queue: :user_submitted for user actions
  config/config.exs
  lib/sequin/databases/databases.ex
  lib/sequin/health/check_http_endpoint_health_worker.ex
  lib/sequin/health/check_postgres_replication_slot_worker.ex
  lib/sequin/health/check_sink_configuration_worker.ex
  lib/sequin/health/kickoff_check_http_endpoint_health_worker.ex
  lib/sequin/health/kickoff_check_postgres_replication_slot_worker.ex
  lib/sequin/health/kickoff_check_sink_configuration_worker.ex
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
  lib/sequin_web/live/databases/show.ex
  lib/sequin_web/live/http_endpoints/form.ex
  lib/sequin_web/live/http_endpoints/show.ex
  lib/sequin_web/live/sink_consumers/show.ex
Labels: enhancement, size:L, lgtm

#1553 Do not randomly switch `legacy_transform` mode on
  test/support/factory/consumers_factory.ex
Labels: size:XS

#1556 Fix heartbeat verification around nil `last_commit_lsn`
  lib/sequin/runtime/slot_processor_server.ex
Labels: bug, size:M

#1554 ✨ Automatically create slots for sequin.yaml
  cli/cli/config_command.go
  cli/config/config.go
  docs/reference/sequin-yaml.mdx
  lib/sequin/databases/databases.ex
  lib/sequin/postgres/postgres.ex
  lib/sequin/replication/replication.ex
  lib/sequin/yaml_loader.ex
  lib/sequin_web/controllers/yaml_controller.ex
  test/sequin/yaml_loader_test.exs
Labels: enhancement, size:L

#1315 💄 Add `create_if_missing` properties for slots + pubs
  cli/cli/config_command.go
  cli/config/config.go
  docs/reference/sequin-yaml.mdx
  lib/sequin/databases/databases.ex
  lib/sequin/postgres/postgres.ex
  lib/sequin/replication/replication.ex
  lib/sequin/transforms/transforms.ex
  lib/sequin/yaml_loader.ex
  lib/sequin_web/controllers/yaml_controller.ex
  test/sequin/postgres_test.exs
  test/sequin/transforms_test.exs
  test/sequin/yaml_loader_test.exs
  test/sequin_web/controllers/yaml_controller_test.exs
Labels: size:XL

#1555 ⚡️ Add indexes to consumer_events
  priv/repo/migrations/20250519232514_add_index_to_consumer_events_for_streaming.exs
Labels: size:S

#1516 Do not preload postgres_database in SinkPipeline - unneeded
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/gcp_pubsub_pipeline.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/runtime/sink_pipeline.ex
  lib/sequin/runtime/sns_pipeline.ex
  lib/sequin/runtime/sqs_pipeline.ex
  lib/sequin/sinks/kafka/kafka.ex
Labels: size:M, lgtm

#1564 ✨ Ignore encrypted headers instead of returning error
  lib/sequin/transforms/transforms.ex
Labels: size:S

#1537 Implement paginated sinks list
  assets/svelte/consumers/SinkIndex.svelte
  lib/sequin/consumers/consumers.ex
  lib/sequin_web/live/sink_consumers/index.ex
  test/sequin/consumers_test.exs
Labels: javascript, size:L, codex

#1565 ⚡️ [nats] Use `idempotency_key` as `Nats-Msg-Id` (deduplication)
  lib/sequin/sinks/nats/client.ex
Labels: size:S

#1567 📝 Update playground.yml, remove database.tables
  docker/playground.yml
Labels: size:XS

#1566 ⚡️ Don't put full SinkConsumer on child specs on production
  lib/sequin/runtime/sink_pipeline.ex
  test/sequin/http_push_pipeline_test.exs
  test/sequin/nats_pipeline_test.exs
  test/sequin/redis_pipeline_test.exs
  test/sequin/sns_pipeline_test.exs
  test/sequin/sqs_pipeline_test.exs
Labels: size:L

#1568 In ConsumerProducer, load the SinkConsumer on boot (memory)
  lib/sequin/runtime/consumer_producer.ex
  lib/sequin/runtime/sink_pipeline.ex
  test/sequin/consumer_producer_test.exs
Labels: size:S

#1569 Init pipeline context inside the processor and batcher stages
  lib/sequin/runtime/sink_pipeline.ex
Labels: size:S

#1578 🐛 Don't restart replication synchronously
  lib/sequin_web/live/transforms/edit.ex
Labels: bug, size:XS

#1561 ♻️ Rename transforms to functions
  assets/svelte/consumers/FunctionPicker.svelte
  assets/svelte/consumers/ShowSink.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/SinkHttpPushForm.svelte
  assets/svelte/consumers/types.ts
  assets/svelte/functions/Edit.svelte
  assets/svelte/functions/Index.svelte
  assets/svelte/functions/types.ts
  assets/svelte/sinks/redis-string/RedisStringSinkCard.svelte
  assets/svelte/sinks/redis-string/RedisStringSinkForm.svelte
  docs/guides/user-webhooks.mdx
  docs/quickstart/elasticsearch.mdx
  docs/quickstart/redis-string.mdx
  docs/quickstart/typesense.mdx
  docs/snippets/function-transform-snippet.mdx
  lib/sequin/application.ex
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/function.ex
  lib/sequin/consumers/path_function.ex
  lib/sequin/consumers/routing_function.ex
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/consumers/transform_function.ex
  lib/sequin/functions/minielixir.ex
  lib/sequin/functions/minielixir/validator.ex
  lib/sequin/functions/test_messages.ex
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
  lib/sequin/runtime/http_push_pipeline.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/runtime/redis_string_pipeline.ex
  lib/sequin/transforms/message.ex
  lib/sequin/transforms/transforms.ex
  lib/sequin/yaml_loader.ex
  lib/sequin_web/controllers/yaml_controller.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/functions/auto_complete.ex
  lib/sequin_web/live/functions/edit.ex
  lib/sequin_web/live/functions/index.ex
  lib/sequin_web/live/sink_consumers/show.ex
  lib/sequin_web/live/transforms/index.ex
  lib/sequin_web/router.ex
  priv/repo/migrations/20250520170347_rename_transforms_to_functions.exs
  test/sequin/functions_test_messages_test.exs
  test/sequin/message_handler_test.exs
  test/sequin/minielixir_test.exs
  test/sequin/postgres_replication_test.exs
  test/sequin/redis_string_pipeline_test.exs
  test/sequin/routing_test.exs
  test/sequin/transforms_test.exs
  test/sequin/yaml_loader_test.exs
  test/sequin_web/live/transform_edit_test.exs
  test/support/factory/consumers_factory.ex
Labels: refactor, size:XL

#1576 ✅ Add tests for filter functions
  lib/sequin/runtime/table_reader.ex
  test/sequin/message_handler_test.exs
  test/sequin/table_reader_test.exs
Labels: size:L

#1577 📝 Filter function docs
  docs/images/reference/filter-component.png
  docs/reference/filters.mdx
Labels: documentation, size:L

#1579 🐛 Restart supervisor tree for path updates
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
Labels: bug, size:S

#1581 ⚙️ Default to NO for delete branch on merge
  scripts/merge.sh
Labels: size:XS

#1593 🐛 Serialize events/record through changesets
  lib/sequin/consumers/consumer_event.ex
  lib/sequin/consumers/consumer_event_data.ex
  lib/sequin/consumers/consumer_record.ex
  lib/sequin/consumers/consumer_record_data.ex
  lib/sequin/consumers/consumers.ex
  test/sequin/consumers_test.exs
  test/sequin/slot_message_store_test.exs
Labels: bug, size:M

#1574 Only load 10k messages from disk at a time
  lib/sequin/runtime/slot_message_store.ex
Labels: size:M

#1580 Add partial index to consumer stream tables where deliver_count >= 1
  priv/repo/migrations/20250521213503_add_partial_index_to_consumer_tables_for_deliver_count_gte_1.exs
Labels: size:M

#1595 🗑️ Delete typsense_sink.import_action (always use :emplace)
  assets/svelte/consumers/types.ts
  lib/sequin/consumers/typesense_sink.ex
  lib/sequin/runtime/typesense_pipeline.ex
  lib/sequin/sinks/typesense/client.ex
  lib/sequin/transforms/transforms.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/sink_consumers/show.ex
Labels: size:S

#1588 💄 Prettify secret errors
  config/runtime.exs
  lib/sequin/config_parser.ex
  test/sequin/config_parser_test.exs
Labels: size:L

#1592 transforms edit page improvements
  assets/svelte/functions/Edit.svelte
  lib/sequin_web/live/functions/edit.ex
Labels: ux-enhancement, size:S

#1590 export filter functions in transforms
  lib/sequin/transforms/transforms.ex
Labels: size:S, lgtm

#1585 don't stop the slot when storage full
  lib/sequin/runtime/slot_message_store.ex
Labels: size:S, lgtm

#1594 [invites] Ensure invites work on self-hosted when self-signup disabled
  .settings.example.json
  config/runtime.exs
  lib/sequin_web/live/user_login_live.ex
  lib/sequin_web/live/user_registration_live.ex
Labels: size:S

#1591 📝 consumer annotations
  lib/sequin/consumers/consumer_event_data.ex
  lib/sequin/consumers/consumer_record_data.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/transforms/transforms.ex
  lib/sequin/yaml_loader.ex
  test/sequin/transforms_test.exs
  test/sequin_web/controllers/sink_consumer_controller_test.exs
  test/sequin_web/controllers/yaml_controller_test.exs
  test/support/factory/consumers_factory.ex
Labels: size:M, lgtm

#1602 ✨ Filter functions on sinks in yaml
  lib/sequin/transforms/transforms.ex
  lib/sequin/yaml_loader.ex
  test/sequin/yaml_loader_test.exs
Labels: enhancement, size:M

#1603 📝 sequin.yaml with functions
  docs/reference/sequin-yaml.mdx
Labels: documentation, size:L

#1607 🐛 Allow removal of transforms, filters, and routing functions
  lib/sequin/transforms/transforms.ex
  lib/sequin/yaml_loader.ex
  test/sequin/yaml_loader_test.exs
  test/support/factory/functions_factory.ex
Labels: bug, size:M

#1608 functions page - limit update modal size
  assets/svelte/functions/Edit.svelte
Labels: ux-enhancement, size:S

#1610 add annotations to sinkconsumer to_external
  lib/sequin/transforms/transforms.ex
Labels: size:XS

#1611 🔐 Add some type safety around message filtering
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/message_handler.ex
Labels: size:M

#1604 [cli] remove logging
  cli/constants/constants.go
  cli/main.go
Labels: cli, size:M, lgtm

#1634 ⚡️ Consumers.list_active_sink_consumers accounts for replication slot
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/health/health.ex
  lib/sequin/runtime/message_consistency_check_worker.ex
  test/sequin/consumers_test.exs
Labels: size:M

#1635 [docker] `sequin` -> `sequin-server`, `sequin-cli` -> `sequin`
  Dockerfile
  lib/sequin/consumers/http_endpoint.ex
  scripts/start_commands.sh
Labels: size:S

#1606 apply yaml from stdin
  cli/config/config.go
  config/runtime.exs
  lib/sequin/yaml_loader.ex
  scripts/start_commands.sh
Labels: cli, size:L, lgtm

#1586 Editable function test messages
  assets/svelte/functions/Edit.svelte
  assets/svelte/functions/EditableArgument.svelte
  assets/svelte/functions/types.ts
  lib/sequin/consumers/consumers.ex
  lib/sequin/functions/minielixir.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin_web/live/functions/edit.ex
Labels: ux-enhancement, size:XL, lgtm

#1623 Redirect to signup page if user is not authenticated after vistiting access invite link
  lib/sequin_web/router.ex
  lib/sequin_web/user_auth.ex
  test/sequin_web/user_auth_test.exs
Labels: enhancement, size:M

#1642 🐛 unbound variable: CONFIG_FILE_PATH
  scripts/start_commands.sh
Labels: size:XS

#1650 🐛 Do not put_restart_wal_cursor! when nil
  lib/sequin/runtime/slot_processor_server.ex
Labels: bug, size:S

#1629 limit height of httpendpoint chooser in sinks page
  assets/svelte/consumers/SinkHttpPushForm.svelte
Labels: javascript, size:XS, lgtm

#1656 [http_push_pipeline] Discard messages that violate SQS message requirements
  lib/sequin/aws/sqs.ex
  lib/sequin/error.ex
  lib/sequin/runtime/http_push_pipeline.ex
  test/sequin/http_push_pipeline_test.exs
Labels: size:L, lgtm

#1657 [http_push_pipeline + sqs] Setup DLQ
  config/runtime.exs
  lib/sequin/application.ex
  lib/sequin/metrics/prometheus.ex
  lib/sequin/runtime/http_push_pipeline.ex
  lib/sequin/runtime/http_push_sqs_pipeline.ex
  test/sequin/http_push_pipeline_test.exs
  test/sequin/http_push_sqs_pipeline_test.exs
Labels: size:L, lgtm

#1660 Add secret-menu env flag for disabling discards
  config/runtime.exs
  lib/sequin/runtime/http_push_sqs_pipeline.ex
  test/sequin/http_push_sqs_pipeline_test.exs
Labels: size:S

#1645 show failure health check when http push via sqs fails to deliver
  lib/sequin/health/event.ex
  lib/sequin/health/health.ex
  lib/sequin/runtime/http_push_sqs_pipeline.ex
  lib/sequin_web/live/sink_consumers/show.ex
Labels: size:M, lgtm

#1663 🐛 Fix dismissable_event date comparison
  lib/sequin/health/health.ex
  test/sequin/health_test.exs
Labels: bug, size:M

#1681 🐛 Prevent patch operations from deleting attached funtions
  lib/sequin/transforms/transforms.ex
  lib/sequin/yaml_loader.ex
  test/sequin_web/controllers/sink_consumer_controller_test.exs
Labels: bug, size:M

#1682 Reduce time interval of `KickoffCheckPostgresReplicationSlotWorker`
  config/config.exs
Labels: size:XS

#1675 use combobox for table selector on functions edit page
  assets/svelte/functions/Edit.svelte
Labels: javascript, size:M, lgtm

#1685 [docs] fix syntax for schema publication
  docs/archive/ingesting-from-postgres.mdx
  docs/connect-postgres.mdx
  docs/reference/databases.mdx
  postgres-replication.md
Labels: documentation, size:S, lgtm

#1624 feat: persist pagination state when navigating to/from sink details
  assets/svelte/consumers/ShowSinkHeader.svelte
  assets/svelte/consumers/SinkIndex.svelte
  assets/svelte/stores/pageStore.ts
  lib/sequin_web/live/sink_consumers/index.ex
Labels: ux-enhancement, size:S, lgtm
