Repository sequinstream/sequin, pull requests merged in 2025-08, with the labels that each got.

#1784 ✨ Add new gauge/metric around entity health
  config/config.exs
  docs/reference/metrics.mdx
  lib/sequin/health/health.ex
  lib/sequin/health/health_snapshot.ex
  lib/sequin/metrics/entity_health_metrics.ex
  lib/sequin/metrics/prometheus.ex
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
  lib/sequin_web/telemetry.ex
  test/sequin/metrics/entity_health_metrics_test.exs
  test/support/factory/health_factory.ex
  test/support/mocks.ex
Labels: documentation, enhancement, size:L, lgtm

#2051 🐛 Set :messages_filtered status for source matching
  lib/sequin/consumers/consumers.ex
  test/sequin/message_handler_test.exs
Labels: bug, size:S, lgtm

#2052 🛠️ Expose `waiting` snapshot statuses as `ok` status in metrics
  lib/sequin/metrics/entity_health_metrics.ex
  test/sequin/metrics/entity_health_metrics_test.exs
Labels: enhancement, size:S, lgtm

#2048 🛠️ prevent 16-byte long strings from being treated as UUID in enrichment process
  lib/sequin/consumers/consumers.ex
  test/sequin/consumers_test.exs
Labels: bug, size:L, lgtm

#2032 🛠️ Lazily load message data in Messages tab
  assets/svelte/consumers/ShowMessages.svelte
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
  lib/sequin_web/live/sink_consumers/show.ex
  test/sequin/slot_message_store_state_test.exs
  test/sequin/slot_message_store_test.exs
Labels: enhancement, size:L, lgtm

#2055 ✨ Retry kafka publish with expo backoff
  lib/sequin/sinks/kafka/client.ex
Labels: sink-kafka, size:M

#2036 📚 Add Minimum Instance Requirements doc
  Makefile
  docs/docs.json
  docs/reference/minimum-requirements.mdx
Labels: documentation, size:M, lgtm

#2025 change meilisearch request method (document replacement)
  docs/reference/sinks/meilisearch.mdx
  lib/sequin/sinks/meilisearch/client.ex
  test/sequin/meilisearch_client_test.exs
  test/sequin/meilisearch_pipeline_test.exs
Labels: documentation, enhancement, size:S, lgtm

#1977 ✨ GCP Pub/Sub fast by default
  docs/reference/sinks/gcp-pubsub.mdx
  lib/sequin/runtime/gcp_pubsub_pipeline.ex
  lib/sequin_web/live/components/consumer_form.ex
  test/sequin/gcp_pubsub_pipeline_test.exs
Labels: sink-gcp-pubsub, size:M

#2028 🤖 ADD-SINK.md
  ADD-SINK.md
Labels: documentation, size:L

#2063 Docs Update - Remove `clustering` reference
  docs/reference/configuration.mdx
Labels: documentation, size:XS, lgtm
