Repository sequinstream/sequin, pull requests merged in 2025-06, with the labels that each got.

#1710 Fix cli args in start commands for interpolate-from-stdin
  scripts/start_commands.sh
Labels: cli, size:XS

#1713 ⚡️ Ack messages outside of SMS
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/sink_pipeline.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_behaviour.ex
  lib/sequin/runtime/slot_message_store_state.ex
  test/sequin/consumer_producer_test.exs
  test/sequin/consumers_test.exs
  test/sequin/slot_message_store_state_test.exs
  test/sequin/slot_message_store_test.exs
  test/sequin/table_reader_server_test.exs
Labels: size:L

#1719 ⚡️ Async start stores and pipeline
  lib/sequin/runtime/slot_supervisor.ex
Labels: enhancement, size:S

#1724 🗑️ Remove slots with old postgres
  lib/sequin/runtime/slot_processor_server.ex
Labels: size:M

#1730 💄 Show better error message when Sequin does not have `usage` on any schemas
  lib/sequin/databases/databases.ex
  lib/sequin/postgres/postgres.ex
Labels: ux-enhancement, size:S

#1739 Add redactor for sensitive logs, remove errors from metadata
  config/runtime.exs
  lib/sequin/logger/redactor.ex
Labels: size:M

#1740 🐛 Fix non-fifo SQS
  lib/sequin/runtime/sqs_pipeline.ex
Labels: bug, sqs, size:S

#1597 👀 Table-fan in?
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/sink_consumer.ex
  test/sequin/message_handler_test.exs
  test/sequin/postgres_replication_test.exs
Labels: size:M

#1612 🗂️ SinkConsumer SchemaFilter
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/schema_filter.ex
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/runtime/slot_message_handler.ex
  priv/repo/migrations/20250523211710_add_schema_filter_to_sink_consumers.exs
  test/sequin/message_handler_test.exs
  test/sequin/postgres_replication_test.exs
  test/support/factory/consumers_factory.ex
Labels: size:L

#1615 💄 TableOrSchemaSelector
  assets/svelte/components/TableOrSchemaSelector.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  lib/sequin_web/live/components/consumer_form.ex
Labels: javascript, size:XL

#1723 ♻️ Backfills with table_oid
  lib/sequin/consumers/backfill.ex
  lib/sequin/runtime/supervisor.ex
  lib/sequin/runtime/table_reader_server.ex
  lib/sequin_web/controllers/backfill_controller.ex
  lib/sequin_web/live/sink_consumers/show.ex
  priv/repo/migrations/20250603233819_add_table_oid_to_backfills.exs
  test/sequin/consumers/backfill_test.exs
  test/sequin/table_reader_server_test.exs
  test/sequin/table_reader_test.exs
  test/support/factory/consumers_factory.ex
Labels: refactor, size:M

#1726 ♻️ sink_consumer.active_backfills (one per table_oid)
  lib/sequin/consumers/backfill.ex
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/iex_helpers.ex
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
  lib/sequin/runtime/supervisor.ex
  lib/sequin/runtime/table_reader.ex
  lib/sequin/runtime/table_reader_server.ex
  lib/sequin/transforms/transforms.ex
  priv/repo/migrations/20250604174541_allow_multiple_active_backfills.exs
  test/sequin/consumers/backfill_test.exs
  test/sequin/table_reader_server_test.exs
  test/sequin/table_reader_test.exs
Labels: size:L

#1731 ♻️ Change seen_pks to be by table_oid
  lib/sequin/application.ex
  lib/sequin/consumers/consumers.ex
  lib/sequin/ets_multiset.ex
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/runtime/table_reader_server.ex
  test/sequin/message_handler_test.exs
  test/sequin/table_reader_server_test.exs
Labels: refactor, size:L

#1729 💄 sink/backfills tab
  assets/svelte/components/BackfillForm.svelte
  assets/svelte/consumers/Backfill.svelte
  assets/svelte/consumers/ShowBackfills.svelte
  assets/svelte/consumers/ShowMessages.svelte
  assets/svelte/consumers/ShowSink.svelte
  assets/svelte/consumers/ShowSinkHeader.svelte
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/init_backfill_stats_worker.ex
  lib/sequin/runtime/starter.ex
  lib/sequin/runtime/table_reader.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/sink_consumers/index.ex
  lib/sequin_web/live/sink_consumers/show.ex
  lib/sequin_web/router.ex
Labels: ux-enhancement, javascript, size:XXL

#1734 ✨ Create backfills on consumer create
  assets/svelte/components/BackfillForm.svelte
  assets/svelte/consumers/ShowSinkHeader.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/types.ts
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/sink_consumers/show.ex
Labels: javascript, size:L

#1737 ✨ SMS with table_oid
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
  test/sequin/slot_message_store_state_test.exs
  test/sequin/slot_message_store_test.exs
Labels: size:L

#1742 ✨ Improve error when non-existing column is used for group columns or column filters
  lib/sequin/transforms/transforms.ex
  lib/sequin/yaml_loader.ex
  test/sequin/yaml_loader_test.exs
Labels: enhancement, size:L

#1744 ✨ Backfills with schema filter
  docs/management-api/backfills/create.mdx
  docs/management-api/backfills/list.mdx
  docs/snippets/backfill-response-snippet.mdx
  lib/sequin/transforms/transforms.ex
  lib/sequin_web/controllers/backfill_controller.ex
  test/sequin_web/controllers/backfill_controller_test.exs
Labels: documentation, size:L

#1745 ♻️ Health on consumers
  lib/sequin/health/health.ex
  lib/sequin/transforms/transforms.ex
Labels: refactor, size:S

#1747 refactor: use compile_env for Kafka module configuration
  lib/sequin/sinks/kafka/kafka.ex
Labels: refactor, kafka, size:S

#1750 ✨ Allow modifying column filters on active sink
  assets/svelte/components/FilterForm.svelte
  lib/sequin/consumers/sequence_filter/column_filter.ex
  test/sequin/consumers_test.exs
Labels: size:L

#1752 ✨ Allow Kafka.test_connection to auto-create topics
  lib/sequin/sinks/kafka/client.ex
Labels: sink-kafka, size:S

#1756 🐛 Use ack_id to fetch message data for messages tab
  assets/svelte/consumers/ShowMessages.svelte
  assets/svelte/outbox/Index.svelte
  lib/sequin/sinks/rabbitmq/client.ex
  lib/sequin_web/live/sink_consumers/show.ex
Labels: bug, size:XL

#1761 🐛 test messages by idempotency key
  assets/svelte/functions/Edit.svelte
  assets/svelte/functions/EditableArgument.svelte
  assets/svelte/functions/types.ts
  lib/sequin/consumers/consumers.ex
  lib/sequin_web/live/functions/edit.ex
Labels: bug, size:M

#1759 fix: move KafkaMock into mock.ex to remove warnings about undefined Kafka functions
  test/support/mocks.ex
  test/test_helper.exs
Labels: bug, kafka, size:XS

#1757 📏 [SystemMetricsServer] Add scheduler utilization
  lib/sequin/system_metrics_server.ex
Labels: enhancement, size:M, lgtm

#1748 feat: automatically restart kafka producers
  lib/sequin/consumers/kafka_sink.ex
Labels: enhancement, kafka, size:XS, lgtm

#1711 feat: implement kafka end-to-end tests
  .github/workflows/e2e-tests.yml
  Makefile
  priv/tests_e2e/README.md
  priv/tests_e2e/docker-compose.yml
  priv/tests_e2e/init.exs
  priv/tests_e2e/postgres/00-setup.sql
  priv/tests_e2e/sequin.yml
  priv/tests_e2e/tests.exs
Labels: kafka, size:XL

#1771 Add expo backoffs to HttpPushPipeline
  lib/sequin/runtime/http_push_sqs_pipeline.ex
  mix.exs
  mix.lock
Labels: dependencies, size:M, lgtm

#1773 📝 Use schema: public in quickstarts
  assets/svelte/components/TableOrSchemaSelector.svelte
  assets/svelte/consumers/GroupColumnsForm.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/functions/Edit.svelte
  docs/images/quickstart/backfill-card.png
  docs/images/quickstart/source-card.png
  docs/quickstart/azure-event-hubs.mdx
  docs/quickstart/gcp-pubsub.mdx
  docs/quickstart/kafka.mdx
  docs/quickstart/kinesis.mdx
  docs/quickstart/nats.mdx
  docs/quickstart/rabbitmq.mdx
  docs/quickstart/redis-stream.mdx
  docs/quickstart/redis-string.mdx
  docs/quickstart/redpanda.mdx
  docs/quickstart/sequin-stream.mdx
  docs/quickstart/sns.mdx
  docs/quickstart/sqs.mdx
  docs/quickstart/typesense.mdx
  docs/quickstart/webhooks.mdx
  docs/snippets/quickstart-backfill-step.mdx
  docs/snippets/quickstart-source-step.mdx
  lib/sequin_web/live/components/consumer_form.ex
Labels: documentation, size:L

#1774 in `CheckSinkConfigurationWorker`, Load db from cached
  lib/sequin/consumers/consumers.ex
  lib/sequin/databases/databases.ex
  lib/sequin/health/check_sink_configuration_worker.ex
  lib/sequin/runtime/database_lifecycle_event_worker.ex
  lib/sequin_web/live/components/consumer_form.ex
Labels: size:M

#1778 ✨ Preload database.sink_consumers through replication slot
  lib/sequin/databases/postgres_database.ex
Labels: size:XS

#1772 Fix telemetry for acknowledged messages
  lib/sequin/consumers/consumers.ex
  lib/sequin/posthog.ex
  lib/sequin/telemetry/posthog_reporter.ex
  test/sequin/posthog_reporter_test.exs
Labels: size:S

#1780 🐛 Support `table missing` in wal pipelins index/show
  assets/svelte/wal_pipelines/Index.svelte
  assets/svelte/wal_pipelines/Show.svelte
  lib/sequin_web/live/wal_pipelines/show.ex
Labels: bug, size:M

#1787 fix: only ignore esc keypress for the function code editor
  assets/svelte/components/FullPageForm.svelte
  assets/svelte/functions/Edit.svelte
Labels: bug, size:S

#1775 🗑️ Remove sink_consumers.source_tables
  assets/svelte/databases/Show.svelte
  lib/mix/tasks/migrate_to_sequences.ex
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/runtime/consumer_producer.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/runtime/table_reader.ex
  lib/sequin_web/live/databases/show.ex
  lib/sequin_web/live/home_live.ex
  lib/sequin_web/live/migration_oct_2024_live.ex
  lib/sequin_web/router.ex
  priv/repo/migrations/20250609234114_drop_sink_consumers_source_tables.exs
  test/sequin/consumers_test.exs
  test/sequin/message_handler_test.exs
  test/sequin/postgres_replication_test.exs
  test/support/factory/consumers_factory.ex
Labels: refactor, size:XXL

#1788 🗑️ Delete Tracer.Server etc.
  lib/sequin/application.ex
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/slot_processor_server.ex
  lib/sequin/tracer/server.ex
  lib/sequin/tracer/starter.ex
  lib/sequin/tracer/state.ex
  lib/sequin/tracer/supervisor.ex
  lib/sequin_web/controllers/pull_controller.ex
  lib/sequin_web/live/databases/show.ex
  test/sequin/tracer/state_test.exs
Labels: refactor, size:XL

#1790 ✨ Add filter trace events
  lib/sequin/runtime/sink_pipeline.ex
Labels: size:S

#1789 💄 TableWithDrawer keyboard commands
  assets/svelte/components/TableWithDrawer.svelte
Labels: javascript, size:L

#1791 ✨ Enable trace for all sinks
  assets/svelte/consumers/ShowSink.svelte
  assets/svelte/consumers/ShowSinkHeader.svelte
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/sink_pipeline.ex
  lib/sequin/runtime/trace.ex
  lib/sequin/transforms/message.ex
Labels: size:M

#1812 June 13, 2025 changelog updates
  CHANGELOG.md
  docs/images/changelog/2025-06-06/backfill-tab.png
  docs/images/changelog/2025-06-06/multiple-tables.png
  docs/images/changelog/2025-06-13/advanced-source-controle.png
Labels: documentation, size:M, lgtm

#1813 📝 Remove column filters from docs
  docs/images/reference/filter-component.png
  docs/reference/filters.mdx
  docs/reference/sequin-yaml.mdx
Labels: size:L

#1814 🩹 include/exclude keys in yaml output
  lib/sequin/transforms/transforms.ex
  test/sequin/transforms_test.exs
Labels: size:S

#1820 ✅ Fix http e2e replication test
  test/sequin/postgres_replication_test.exs
Labels: size:M

#1803 :recycle: Move flushing out of handle_data
  lib/sequin/runtime/slot_processor_server.ex
Labels: refactor, size:L, lgtm

#1804 :recycle: Buffer messages as opposed to disconnecting
  lib/sequin/postgres/replication_connection.ex
  lib/sequin/runtime/slot_processor_server.ex
  test/sequin/postgres_replication_test.exs
Labels: refactor, size:L, lgtm

#1818 ♻️ Assert that we receive at most one bufferable message
  lib/sequin/postgres/replication_connection.ex
Labels: refactor, size:S

#1795 Add S2 sink
  assets/svelte/consumers/ShowSink.svelte
  assets/svelte/consumers/ShowSinkHeader.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/SinkIndex.svelte
  assets/svelte/consumers/types.ts
  assets/svelte/sinks/s2/S2Icon.svelte
  assets/svelte/sinks/s2/S2SinkCard.svelte
  assets/svelte/sinks/s2/S2SinkForm.svelte
  config/test.exs
  lib/sequin/consumers/s2_sink.ex
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/logger/redactor.ex
  lib/sequin/runtime/s2_pipeline.ex
  lib/sequin/runtime/sink_pipeline.ex
  lib/sequin/sinks/s2/client.ex
  lib/sequin/transforms/transforms.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/sink_consumers/show.ex
  test/sequin/s2_client_test.exs
  test/sequin/s2_pipeline_test.exs
  test/sequin/yaml_loader_test.exs
  test/support/factory/consumers_factory.ex
  test/support/factory/destination_factory.ex
Labels: size:XL

#1826 🩹 Fix Counter.inc to allow non-one counts
  lib/sequin/metrics/prometheus.ex
Labels: size:M

#1829 :zap: Improve default performance
  assets/svelte/consumers/SinkConsumerForm.svelte
  docs/reference/sinks/overview.mdx
  lib/sequin/runtime/kafka_pipeline.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/runtime/sink_pipeline.ex
  lib/sequin/runtime/slot_message_store_state.ex
  lib/sequin/runtime/slot_processor_server.ex
Labels: enhancement, size:M, lgtm

#1831 ♻️ Refactor ProcessMetrics to use frames/exclusive metrics
  lib/sequin/process_metrics.ex
Labels: size:L

#1833 🩹 Make YAML and API backwards compatible with table/schema fields
  assets/svelte/components/FullPageForm.svelte
  lib/sequin/transforms/transforms.ex
  test/sequin_web/controllers/sink_consumer_controller_test.exs
Labels: size:M

#1835 ⚙️ Kafka profile
  docker-compose.yaml
Labels: size:M

#1834 S2 Sink Docs
  docs/docs.json
  docs/how-to/stream-postgres-to-s2.mdx
  docs/introduction.mdx
  docs/management-api/sink-consumers/create.mdx
  docs/quickstart/s2.mdx
  docs/reference/sinks/s2.mdx
  docs/snippets/sink-consumer-response-snippet.mdx
  docs/snippets/sink-consumer-single-response-example-snippet.mdx
Labels: documentation, size:L, lgtm

#1837 Search index guide clean
  docs/docs.json
  docs/how-to/sync-search-indexes.mdx
Labels: documentation, size:L

#1836 ♻️ %ProcessMetrics.Metrics{}
  lib/sequin/process_metrics.ex
Labels: refactor, size:L

#1838 📏 ProcessMetrics to prometheus
  docker/dashboard.json
  lib/sequin/metrics/prometheus.ex
  lib/sequin/process_metrics.ex
  lib/sequin/runtime/slot_message_handler.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_processor_server.ex
Labels: size:XL

#1840 ✨ Add process metrics graphs to default grafana
  grafana/dashboards/sequin.json
Labels: size:L

#1841 🤫 do not tcp connect for endpoint health checks
  assets/svelte/http_endpoints/Show.svelte
  lib/sequin/health/check_http_endpoint_health_worker.ex
  lib/sequin/metrics/metrics.ex
  lib/sequin_web/live/http_endpoints/show.ex
Labels: size:M

#1845 Do not add delivered wal_cursors to idempotency metadata (noisy)
  lib/sequin/runtime/sink_pipeline.ex
Labels: size:XS

#1847 🔧 Fix esbuild-svelte warning
  assets/svelte/components/FilterForm.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/wal_pipelines/Form.svelte
Labels: size:XS

#1852 🐛 Fix group_id=nil regression for tables w/o pks
  lib/sequin/runtime/message_handler.ex
  test/sequin/message_handler_test.exs
  test/sequin/slot_message_store_state_test.exs
Labels: bug, size:M

#1839 docs: update remaining references to records
  docs/guides/cloudflare.mdx
  docs/guides/inngest.mdx
  docs/guides/lambda.mdx
  docs/guides/supabase-function.mdx
  docs/guides/supabase-webhooks.mdx
  docs/guides/tinybird.mdx
  docs/guides/trigger-dev.mdx
  docs/guides/vercel.mdx
  docs/how-to/annotate-changes.mdx
  docs/how-to/create-audit-logs.mdx
  docs/how-to/replicate-tables.mdx
  docs/how-to/stream-postgres-to-a-webhook-endpoint.mdx
  docs/how-to/stream-postgres-to-aws-lambda.mdx
  docs/how-to/stream-postgres-to-azure-event-hubs.mdx
  docs/how-to/stream-postgres-to-gcp-pubsub.mdx
  docs/how-to/stream-postgres-to-kafka.mdx
  docs/how-to/stream-postgres-to-nats.mdx
  docs/how-to/stream-postgres-to-rabbitmq.mdx
  docs/how-to/stream-postgres-to-redis-stream.mdx
  docs/how-to/stream-postgres-to-sequin-stream.mdx
  docs/how-to/stream-postgres-to-sns.mdx
  docs/how-to/stream-postgres-to-sqs.mdx
  docs/how-to/trigger-automated-workflows.mdx
  docs/postgres-change-data-capture.mdx
  docs/quickstart/azure-event-hubs.mdx
  docs/quickstart/gcp-pubsub.mdx
  docs/quickstart/kafka.mdx
  docs/quickstart/nats.mdx
  docs/quickstart/rabbitmq.mdx
  docs/quickstart/redis-stream.mdx
  docs/quickstart/redpanda.mdx
  docs/quickstart/sqs.mdx
  docs/quickstart/webhooks.mdx
  docs/reference/annotations.mdx
  docs/reference/backfills.mdx
  docs/reference/change-retention.mdx
  docs/reference/databases.mdx
  docs/reference/filters.mdx
  docs/reference/messages.mdx
  docs/reference/routing.mdx
  docs/reference/sequin-stream-api/receive.mdx
  docs/reference/sinks/gcp-pubsub.mdx
  docs/reference/sinks/overview.mdx
  docs/reference/sinks/redis-stream.mdx
  docs/reference/sinks/sequin-stream.mdx
  docs/reference/sinks/sns.mdx
  docs/reference/sinks/sqs.mdx
  docs/reference/sinks/webhooks.mdx
  docs/reference/transforms.mdx
Labels: size:L

#1854 ✅ Comprehensive end-to-end YAML tests
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/transforms/transforms.ex
  test/sequin/transforms_test.exs
  test/sequin_web/controllers/yaml_controller_test.exs
  test/support/factory/consumers_factory.ex
Labels: size:L

#1855 Add WalSenderMonitor
  config/runtime.exs
  lib/sequin/application.ex
  lib/sequin/list.ex
  lib/sequin/runtime/wal_sender_monitor.ex
Labels: enhancement, size:L

#1856 ⛓️ :link instead of :monitor SPS <-> SMS
  lib/sequin/runtime/consumer_lifecycle_event_worker.ex
  lib/sequin/runtime/slot_message_store.ex
  lib/sequin/runtime/slot_message_store_state.ex
  lib/sequin/runtime/slot_processor_server.ex
  lib/sequin/runtime/slot_supervisor.ex
  test/sequin/slot_message_store_test.exs
Labels: size:L

#1862 ⚡️ [gcp pubsub] Improve throughput by fixing batching and ordering key
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/consumers/source_table.ex
  lib/sequin/runtime/gcp_pubsub_pipeline.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/string.ex
  test/sequin/yaml_loader_test.exs
Labels: sink-gcp-pubsub, size:M, lgtm

#1864 ✨ Add `metadata.database` object to all messages
  assets/svelte/components/MessageExamples.svelte
  assets/svelte/components/TransformExamples.svelte
  docs/guides/inngest.mdx
  docs/guides/supabase-webhooks.mdx
  docs/how-to/annotate-changes.mdx
  docs/how-to/stream-postgres-to-aws-lambda.mdx
  docs/quickstart/sequin-stream.mdx
  docs/reference/messages.mdx
  docs/reference/sequin-stream-api/receive.mdx
  docs/reference/sinks/sequin-stream.mdx
  docs/reference/sinks/webhooks.mdx
  lib/sequin/consumers/consumer_event_data.ex
  lib/sequin/consumers/consumers.ex
  lib/sequin/consumers/path_function.ex
  lib/sequin/runtime/message_handler.ex
  lib/sequin/runtime/table_reader.ex
  test/sequin/consumers_test.exs
  test/sequin/http_push_pipeline_test.exs
  test/support/factory/consumers_factory.ex
Labels: documentation, size:XL, lgtm

#1865 ✨ Add DebouncedLogger
  lib/sequin/application.ex
  lib/sequin/debounced_logger.ex
  lib/sequin/runtime/sink_pipeline.ex
  test/sequin/debounced_logger_test.exs
Labels: enhancement, size:L

#1879 💄 Better formatting for errors from the cli during config apply
  cli/config/config.go
Labels: size:M

#1868 ✨ Add routing to Kafka
  assets/svelte/consumers/DynamicRoutingForm.svelte
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/dynamicRoutingDocs.ts
  assets/svelte/consumers/types.ts
  assets/svelte/functions/Edit.svelte
  assets/svelte/sinks/kafka/KafkaSinkForm.svelte
  docs/reference/routing.mdx
  lib/sequin/consumers/kafka_sink.ex
  lib/sequin/consumers/routing_function.ex
  lib/sequin/consumers/sink_consumer.ex
  lib/sequin/runtime/kafka_pipeline.ex
  lib/sequin/runtime/routing/consumers/kafka.ex
  lib/sequin/runtime/routing/routing.ex
  lib/sequin/sinks/kafka/client.ex
  lib/sequin/sinks/kafka/connection_cache.ex
  lib/sequin/sinks/kafka/kafka.ex
  lib/sequin_web/live/components/consumer_form.ex
  lib/sequin_web/live/functions/edit.ex
  test/sequin/kafka_sink_test.exs
Labels: enhancement, kafka, size:L

#1882 Add docs footer links
  docs/docs.json
Labels: documentation, size:M

#1880 🤖 ADD-SINK-ROUTING.md for agents
  ADD-SINK-ROUTING.md
  test/support/factory/functions_factory.ex
Labels: documentation, size:L

#1886 [Docs] update introduction
  docs/images/introduction/azure.png
  docs/images/introduction/database-zap.svg
  docs/images/introduction/elastic.png
  docs/images/introduction/kafka.png
  docs/images/introduction/kinesis.png
  docs/images/introduction/meilisearch.png
  docs/images/introduction/nats.png
  docs/images/introduction/pub-sub.png
  docs/images/introduction/rabbit.png
  docs/images/introduction/redis-1.png
  docs/images/introduction/redis-2.png
  docs/images/introduction/s2.png
  docs/images/introduction/sequin-stream.png
  docs/images/introduction/sns.png
  docs/images/introduction/sqs.png
  docs/images/introduction/typesense.png
  docs/images/introduction/webhook.png
  docs/introduction.mdx
Labels: size:L

#1887 Improve docs landing
  docs/images/introduction/kafka.svg
  docs/images/introduction/sequin-stream.svg
  docs/introduction.mdx
Labels: documentation, size:S

#1885 Add Typesense routing support
  assets/svelte/consumers/SinkConsumerForm.svelte
  assets/svelte/consumers/dynamicRoutingDocs.ts
  assets/svelte/consumers/types.ts
  assets/svelte/functions/Edit.svelte
  assets/svelte/sinks/typesense/TypesenseSinkCard.svelte
  assets/svelte/sinks/typesense/TypesenseSinkForm.svelte
  docs/reference/routing.mdx
  docs/reference/sinks/typesense.mdx
  lib/sequin/consumers/routing_function.ex
  lib/sequin/consumers/typesense_sink.ex
  lib/sequin/runtime/routing/consumers/typesense.ex
  lib/sequin/runtime/routing/routing.ex
  lib/sequin/runtime/typesense_pipeline.ex
  lib/sequin_web/live/functions/edit.ex
  test/sequin/typesense_pipeline_test.exs
  test/sequin/typesense_sink_test.exs
  test/sequin/yaml_loader_test.exs
  test/support/factory/functions_factory.ex
Labels: size:L, codex

#1890 🐛 Fix NATS routing details in NatsSinkCard
  assets/svelte/sinks/nats/NatsSinkCard.svelte
Labels: bug, sink-nats, size:S

#1893 🩹 Add routing_mode to ConsumersFactory for sinks which have it
  test/support/factory/consumers_factory.ex
Labels: size:XS

#1892 ♻️ Refactor slot message -> consumer message into shared functions
  lib/sequin/consumers/consumers.ex
  lib/sequin/runtime/message.ex
  lib/sequin/runtime/message_handler.ex
Labels: refactor, size:XL
